const trainingData = [
    { input: 'I am super happy!', output: 'happy' },
    { input: 'What a trhill!', output: 'bad' },
    { input: 'Food was delicious, awesome service', output: 'happy' },
    { input: 'This is the best food ever', output: 'happy' },
    { input: 'I am 100% satisfied', output: 'happy' },
    { input: 'I am 95% satisfied', output: 'happy' },
    { input: 'I hated the service and the food', output: 'bad' },
    { input: 'Would not recommend to anyone', output: 'bad' },
    { input: 'This is the worst place to eat in Montreal', output: 'bad' },
    { input: 'I am 95% satisfied', output: 'happy' },
    { input: 'I was happy with my order', output: 'happy' },
    { input: 'I am happy!', output: 'happy' },
    { input: 'The food was terrible', output: 'bad' },
    { input: 'I would never order from there again', output: 'bad' },
    { input: 'I was disapointed', output: 'bad' },
    { input: 'I was very disapointed', output: 'bad' },
    { input: 'The food tasted like shit', output: 'bad' },
    { input: 'The food tasted like crap', output: 'bad' },
    { input: 'OMG best service', output: 'happy' },
    { input: 'I would recommend it to my friends', output: 'happy' },
    { input: 'Delicious food, great service', output: 'happy' },
    { input: 'Best choice out there', output: 'happy' },
    { input: 'quick delivery, fast and effective', output: 'happy' },
    { input: 'I would not recommend', output: 'bad' },
    { input: 'I would not recommend to my friends', output: 'bad' },
    { input: 'Very large choice of meals, easy to order and interesting offers to watch for. Great!', output: 'happy' },
    { input: 'I already set a record for ordering from @ALaCarteExpress every week. Today, I ordered twice.', output: 'happy' },
    { input: 'Very satisfied with ALCE, they take care when delivering, always on time. Great variety of choices.', output: 'happy' },
    { input: 'Very bad quality and slow', output: 'bad' },
    { input: 'bad and slow', output: 'bad' },
    { input: 'I was very disapointed with my order', output: 'bad' },
    { input: 'the vegetables where rotten', output: 'bad' },
    { input: 'taste was weird', output: 'bad' },
    { input: 'Really bad first experice', output: 'bad' },
    { input: 'bad after sale service', output: 'bad' },
    { input: 'taste was not what I expected', output: 'bad' },
    { input: 'I had to put it to the garbage', output: 'bad' },
    { input: 'Bad experience', output: 'bad' },
    { input: 'I had a really bad experience with them', output: 'bad' },
    { input: 'alot of errors in my order', output: 'bad' },
    { input: 'I was very happy with my order', output: 'happy' },
    { input: 'This looks really bad', output: 'bad' },
    { input: 'I was very happy with my order', output: 'happy' },
    { input: 'I really did not liked the spagetthi', output: 'bad' },
    { input: 'I had to trow half the food to the garbage', output: 'bad' },
    { input: 'I had a bad experience ordering with them', output: 'bad' },


];