const trainingData = [
    { input: 'i am super happy', output: 'happy' },
    { input: 'what a trhill', output: 'bad' },
    { input: 'food was delicious awesome service', output: 'happy' },
    { input: 'this is the best food ever', output: 'happy' },
    { input: 'i am satisfied', output: 'happy' },
    { input: 'I am satisfied', output: 'happy' },
    { input: 'i hated the service and the food', output: 'bad' },
    { input: 'would not recommend to anyone', output: 'bad' },
    { input: 'this is the worst place to eat in montreal', output: 'bad' },
    { input: 'i am satisfied', output: 'happy' },
    { input: 'i was happy with my order', output: 'happy' },
    { input: 'i am happy!', output: 'happy' },
    { input: 'the food was terrible', output: 'bad' },
    { input: 'i would never order from there again', output: 'bad' },
    { input: 'i was disapointed', output: 'bad' },
    { input: 'i was very disapointed', output: 'bad' },
    { input: 'the food tasted like shit', output: 'bad' },
    { input: 'the food tasted like crap', output: 'bad' },
    { input: 'omg best service', output: 'happy' },
    { input: 'i would recommend it to my friends', output: 'happy' },
    { input: 'delicious food, great service', output: 'happy' },
    { input: 'best choice out there', output: 'happy' },
    { input: 'quick delivery, fast and effective', output: 'happy' },
    { input: 'i would not recommend', output: 'bad' },
    { input: 'i would not recommend it to my friends', output: 'bad' },
    { input: 'very large choice of meals easy to order and interesting offers to watch for great', output: 'happy' },
    { input: 'i already set a record for ordering from them every week today i ordered twice', output: 'happy' },
    { input: 'very satisfied with alce they take care when delivering always on time great variety of', output: 'happy' },
    { input: 'very bad quality and slow', output: 'bad' },
    { input: 'bad and slow', output: 'bad' },
    { input: 'i was very disapointed with my order', output: 'bad' },
    { input: 'the vegetables where rotten', output: 'bad' },
    { input: 'taste was weird', output: 'bad' },
    { input: 'really bad first experice', output: 'bad' },
    { input: 'bad after sale service', output: 'bad' },
    { input: 'taste was not what i expected', output: 'bad' },
    { input: 'i had to put it to the garbage', output: 'bad' },
    { input: 'bad experience', output: 'bad' },
    { input: 'i had a really bad experience with them', output: 'bad' },
    { input: 'alot of errors in my order', output: 'bad' },
    { input: 'i was very happy with my order', output: 'happy' },
    { input: 'this looks really bad', output: 'bad' },
    { input: 'i was very happy with my order', output: 'happy' },
    { input: 'i really did not liked the spagetthi', output: 'bad' },
    { input: 'i had to trow half the food to the garbage', output: 'bad' },
    { input: 'i had a bad experience ordering with them', output: 'bad' },
    { input: 'bad bad bad', output: 'bad' },
    { input: 'bad', output: 'bad' },
    { input: 'hi', output: 'happy' },
    { input: 'review content', output: 'happy' },
    { input: 'asdf', output: 'bad' },
    { input: 'ghjghjghj', output: 'bad' },
    { input: 'hello', output: 'happy' },
    { input: 'good', output: 'happy' },
    { input: 'very good', output: 'happy' },
    { input: 'This is very good !', output: 'happy' },
    { input: 'this is very good', output: 'happy' },
    { input: 'I want to kill myself', output: 'bad' },
    { input: 'I want to kill myself !', output: 'bad' },
    { input: 'i want to kill myself', output: 'bad' },
    { input: 'I would never eat food from them again', output: 'bad' },
    { input: 'I did not liked my experience', output: 'bad' },
    { input: 'I can eat this all day !', output: 'happy' },
    { input: 'i can eat this all day', output: 'happy' },
    { input: 'the portions where too small', output: 'bad' },
    { input: 'total ripoff', output: 'bad' },
    { input: 'steal', output: 'bad' },
    { input: 'never again !', output: 'bad' },
    { input: 'dogshit', output: 'bad' },
    { input: 'horseshit', output: 'bad' },
    { input: 'crap', output: 'bad' },
    { input: 'this sucks', output: 'bad' },
    { input: 'evil', output: 'bad' },
    { input: 'horrible value', output: 'bad' },
    { input: 'horrible taste, would not recommend', output: 'bad' },
    { input: 'horrible taste, would not order again', output: 'bad' },
    { input: 'would not order again', output: 'bad' },
    { input: 'Would not order again !', output: 'bad' },
    { input: 'I was sick for 2 days after eating a meal', output: 'bad' },
    { input: 'I was sick for 3 days after eating a meal', output: 'bad' },
    { input: 'I was sick for 1 days after eating a meal', output: 'bad' },
    { input: 'I was sick for 1 hour after eating a meal', output: 'bad' },
    { input: 'I was sick after eating a meal', output: 'bad' },
    { input: 'I wanted to vomit', output: 'bad' },
    { input: 'I wanted to vomit after eating', output: 'bad' },
]